thoth-station/python

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .zuul.yaml, pyproject.toml
Signed-off-by: Christoph Görn <goern@redhat.com>
=> adding standard thoth project configs

thoth/python/source.py
Sometimes we got wrong package names as links can also include ".", ".." in
link names. This patch respects PEEP for Python simple API index.
=> Improve packages gathering from indexes

.coafile, .zuul.yaml
implements #18 
Signed-off-by: Christoph Görn <goern@redhat.com>
=> added pytest jobs to all the pipes

thoth/python/pipfile.py, thoth/python/project.py
* add space after words correctly
* default to an empty dict in requires section
=> Minor fixes in implementation

thoth/python/project.py
=> Requires are optional field in Pipfile

thoth/python/source.py
thoth.python.source._download_artifacts_sha() is the place where actual .whl file download process is happening. So, we added to this function another attribute with_included_files: bool = False. 
And now in digests-fetcher inside fetch.py we can issue self.source.get_package_hashes(package_name, package_version, True) to gather hashes for internal files of .whl file. Example JSON response:
```json
[
{
"name": "tensorflow-1.10.0-cp27-cp27m-macosx_10_11_x86_64.whl",
"sha256": "9eb5d117089b5cfa33c6dd32fd05574662a8167de53b686708b683e4af9bc687",
"included_files": {
"tensorflow-1.10.0.data/purelib/tensorflow/api_template.__init__.py": "aea7dac16d1ae0b03da0ba0efc0afda29e2841ab356a9b65df7739bb37810a90",
"tensorflow-1.10.0.data/purelib/tensorflow/__init__.py": …
```
=> gathering hashes for .whl files

thoth/python/source.py
Fixes [Fetching digests for package 'selinon' in version '1.0.0' from 'https://pypi.org/simple' fails](https://github.com/thoth-station/package-analyzer/issues/20)
=> extracting tar.gz files

tests/data/tensorflow_serving_api-1.13.0-py2.py3-none-any.json, tests/test_source.py, thoth/python/source.py
Changed the output of package-analyzer from tree format to list of filepath and sha256.
=> Output filepath and sha256 for all files inside artifact

tests/data/pipfiles/Pipfile_test1.lock, tests/test_package_version.py, thoth/python/package_version.py
Fixes: https://github.com/thoth-station/adviser/issues/349
=> Normalize Python package names according to PEP-0503

thoth/python/artifact.py
FIxes https://github.com/thoth-station/python/issues/121
=> Fix temporary name assignment

thoth/python/artifact.py
- Fixes syncing issue. As set is not JSON serializable we change it to list.
=> fix symbols

thoth/python/project.py
Related: https://github.com/thoth-station/adviser/issues/389
=> Fix incosistent runtime environment attribute instantiation

Pipfile, Pipfile.lock, requirements.txt, tests/test_package_version.py, thoth/python/package_version.py
Relates: https://github.com/thoth-station/storages/issues/1013
=> Normalize Python package versions according to PEP-440

thoth/python/package_version.py
=> Use packaging for package name normalization

Pipfile.lock, thoth/python/package_version.py
=> Do not rely on pkg_resources, use packaging for version parsing

tests/test_package_version.py, thoth/python/package_version.py
It's not used anywhere, also, start using packaging in its full power.
=> Drop version specification

thoth/python/source.py
Related: https://github.com/thoth-station/solver/pull/357
=> Introduce a method for checking if the given package is provided by index

.coafile, docs/source/conf.py
Related: https://github.com/thoth-station/nepthys/pull/16
=> Change Sphinx theme

thoth/python/source.py
Additional location of the TODO from #115
=> Add change to the other TODO

Pipfile, Pipfile.lock
=> Remove typeshed from requirements

thoth/python/artifact.py
Related-To: https://github.com/thoth-station/package-analyzer/issues/114
=> Be explicit about errors

Pipfile.lock, thoth/python/package_version.py
This significantly speeds up the adviser and reduces the memory footprint.
=> Cache properties of PackageVersion

thoth/python/source.py
Get the date and time of the release. Useful data analysis with respect to time.
=> Get release time

setup.py
Related: https://github.com/thoth-station/python/pull/277
=> Increase pytest timeout

thoth/python/aiosource.py
Some of the functions that were missing from `aiosource` can't be called by the super class `source` because their dependent functions are already implemented in an asynchronous function which needs to be awaited to get results. Without calling `await` we only get a `coroutine` object.
=> add more functions to aiosource

thoth/python/source.py
Signed-off-by: Francesco Murdaca <fmurdaca@redhat.com>
=> Adjust docstring

.thoth.yaml
Signed-off-by: Francesco Murdaca <fmurdaca@redhat.com>
=> Add maintainers

tests/test_helpers.py, tests/test_project.py, thoth/python/source.py
Fixes: https://github.com/thoth-station/adviser/issues/1610
=> Adjust how source name is derived

thoth/python/aiosource.py
=> Fix testsuite for Python 3.8

.pre-commit-config.yaml, tests/data/pipfiles/Pipfile_thoth, tests/test_pipfile.py, tests/test_provenance.py, thoth/python/pipfile.py, thoth/python/project.py, thoth/python/source.py
Related: https://github.com/thoth-station/thoth-application/issues/816
=> Introduce Thoth section in Pipfile

tests/test_package_version.py, thoth/python/package_version.py
Fixes: https://github.com/thoth-station/thamos/issues/728
=> Raise an error if editable installs are used

tests/data/pipfiles/Pipfile_thoth, tests/test_pipfile.py, thoth/python/pipfile.py
=> Introduce disable index adjustment in Thoth's section in Pipfile

tests/test_pipfile.py, thoth/python/exceptions.py, thoth/python/package_version.py, thoth/python/packages.py, thoth/python/pipfile.py, thoth/python/project.py
Related: https://github.com/thoth-station/thamos/issues/745
=> Add routines to support adding packages to Pipfile

thoth/python/pipfile.py, thoth/python/project.py
Related: https://github.com/thoth-station/thamos/issues/745
=> Optionally keep thoth specific configuration in Pipfile

thoth/python/pipfile.py
=> fridex Override entries in Thoth section if they do not meet type expected

thoth/python/pipfile.py, thoth/python/project.py
=> Fix serialization and loading of requirements files

thoth/python/pipfile.py
=> Copy dict before performing pop

tests/test_pipfile.py, thoth/python/package_version.py, thoth/python/pipfile.py, thoth/python/project.py
Fixes: https://github.com/thoth-station/adviser/issues/1710
=> Version identifier should be always non-None value

.prow.yaml, thoth/python/project.py
Related: https://github.com/thoth-station/thamos/issues/785
Related: https://github.com/thoth-station/adviser/pull/1730/
=> Optionally keep Thoth section when generating project

.prow.yaml
Add mypy check to repo. Only check `thoth-python` library files and ignore missing imports.
=> add prow check with specific args

thoth/python/pipfile.py
=> Fix serialization of packages without version specifier

tests/data/constraints/constraints_0.txt, tests/data/constraints/constraints_1.txt, tests/data/constraints/constraints_2.txt, tests/data/constraints/constraints_3.txt, tests/test_constraints.py, thoth/python/__init__.py, thoth/python/constraints.py, thoth/python/exceptions.py, thoth/python/helpers.py, thoth/python/project.py
Related: https://github.com/thoth-station/core/issues/271
=> Add support for constraints

thoth/python/project.py
=> Instantiate Pipfile instance just once

.aicoe-ci.yaml, .prow.yaml, .thoth.yaml
update the prow resource limits
Signed-off-by: Harshad Reddy Nalla <hnalla@redhat.com>
Related-to: https://github.com/thoth-station/thoth-application/issues/1332
=> update the prow resource limits

thoth/python/project.py
Related: https://github.com/thoth-station/thamos/issues/906
=> Describe where files are looked up on an error

thoth/python/package_version.py
Fixes: https://github.com/thoth-station/python/issues/425
=> Perform shallow copy when parsing Pipfile package entry

.pre-commit-config.yaml, .prow.yaml, tests/test_aiosource.py, tests/test_package_version.py, tests/test_source.py, thoth/python/package_version.py
Signed-off-by: Francesco Murdaca <fmurdaca@redhat.com>
=> Add tests for decoded artifact for package versions

tests/test_project.py, thoth/python/project.py
Fixes: https://github.com/thoth-station/adviser/issues/2246
=> Check lockfile hash on provenance checks

thoth/python/aiosource.py, thoth/python/source.py
Fixes: https://github.com/thoth-station/python/issues/450
=> Fix artifact obtaining on the Pulp instance

thoth/python/project.py
=> Fix typo in error message

thoth/python/aiosource.py, thoth/python/source.py
Related: https://github.com/thoth-station/integration-tests/issues/259
=> Fix constructing artifact url

.thoth.yaml
=> use thoth-advise manager instead of update manager

.pre-commit-config.yaml, .prow.yaml, .thoth.yaml, OWNERS
This PR also updates pre-commit configuration URLs as per https://github.com/thoth-station/thoth-application/issues/2111
No
- Update `pre-commit` configuration to latest versions and protocol
- Add myself as approver
- Remove maintainers from `.thoth.yaml` so that the `OWNERS` approver list is used
=> Add myself to owners

.pre-commit-config.yaml, .prow.yaml, OWNERS, thoth/python/project.py
HouseKeeping: Updated pre-commit and OWNERS
Signed-off-by: Harshad Reddy Nalla <hnalla@redhat.com>
=> :recycle: HouseKeeping: Updated pre-commit and OWNERS
